const products = [
  {
    id: 1,
    imgUrl: 'https://source.unsplash.com/300x300/?butter-chicken',
    name: 'Butter Chicken',
    description: 'Rich and creamy Indian chicken curry.',
    rating: 4.5,
    price: 1099,
    discountedPrice: 769,
    discountPercentage: 30,
    type: 'dish',
    category: 'Indian',
  },
  {
    id: 2,
    imgUrl: 'https://source.unsplash.com/300x300/?biryani',
    name: 'Chicken Biryani',
    description: 'Aromatic rice with spices.',
    rating: 4.8,
    price: 899,
    discountedPrice: 699,
    discountPercentage: 22,
    type: 'cuisine',
    category: 'Indian',
  },
  {
    id: 3,
    imgUrl: 'https://source.unsplash.com/300x300/?paneer',
    name: 'Paneer Butter Masala',
    description: 'Creamy paneer curry.',
    rating: 4.2,
    price: 799,
    discountedPrice: 599,
    discountPercentage: 25,
    type: 'dish',
    category: 'Indian',
  },
  {
    id: 4,
    imgUrl: 'https://source.unsplash.com/300x300/?dal',
    name: 'Dal Tadka',
    description: 'Spiced lentil dish.',
    rating: 3.9,
    price: 499,
    discountedPrice: 349,
    discountPercentage: 30,
    type: 'dish',
    category: 'Indian',
  },
  {
    id: 5,
    imgUrl: 'https://source.unsplash.com/300x300/?naan',
    name: 'Butter Naan',
    description: 'Soft Indian bread.',
    rating: 3.7,
    price: 199,
    discountedPrice: 149,
    discountPercentage: 25,
    type: 'dish',
    category: 'Indian',
  },

  {
    id: 6,
    imgUrl: 'https://source.unsplash.com/300x300/?noodles',
    name: 'Hakka Noodles',
    description: 'Stir-fried noodles.',
    rating: 4.1,
    price: 499,
    discountedPrice: 349,
    discountPercentage: 30,
    type: 'dish',
    category: 'Chinese',
  },
  {
    id: 7,
    imgUrl: 'https://source.unsplash.com/300x300/?fried-rice',
    name: 'Fried Rice',
    description: 'Rice with veggies.',
    rating: 4.0,
    price: 399,
    discountedPrice: 299,
    discountPercentage: 25,
    type: 'dish',
    category: 'Chinese',
  },
  {
    id: 8,
    imgUrl: 'https://source.unsplash.com/300x300/?spring-roll',
    name: 'Spring Rolls',
    description: 'Crispy rolls.',
    rating: 3.8,
    price: 299,
    discountedPrice: 199,
    discountPercentage: 33,
    type: 'dish',
    category: 'Chinese',
  },
  {
    id: 9,
    imgUrl: 'https://source.unsplash.com/300x300/?manchurian',
    name: 'Manchurian',
    description: 'Spicy gravy balls.',
    rating: 4.3,
    price: 549,
    discountedPrice: 399,
    discountPercentage: 27,
    type: 'dish',
    category: 'Chinese',
  },
  {
    id: 10,
    imgUrl: 'https://source.unsplash.com/300x300/?dimsum',
    name: 'Dimsum',
    description: 'Steamed dumplings.',
    rating: 4.6,
    price: 699,
    discountedPrice: 499,
    discountPercentage: 28,
    type: 'cuisine',
    category: 'Chinese',
  },

  {
    id: 11,
    imgUrl: 'https://source.unsplash.com/300x300/?pizza',
    name: 'Margherita Pizza',
    description: 'Classic pizza.',
    rating: 4.4,
    price: 799,
    discountedPrice: 599,
    discountPercentage: 25,
    type: 'dish',
    category: 'Italian',
  },
  {
    id: 12,
    imgUrl: 'https://source.unsplash.com/300x300/?pasta',
    name: 'White Sauce Pasta',
    description: 'Creamy pasta.',
    rating: 4.2,
    price: 699,
    discountedPrice: 499,
    discountPercentage: 28,
    type: 'dish',
    category: 'Italian',
  },
  {
    id: 13,
    imgUrl: 'https://source.unsplash.com/300x300/?lasagna',
    name: 'Lasagna',
    description: 'Layered pasta dish.',
    rating: 4.7,
    price: 999,
    discountedPrice: 749,
    discountPercentage: 25,
    type: 'cuisine',
    category: 'Italian',
  },
  {
    id: 14,
    imgUrl: 'https://source.unsplash.com/300x300/?risotto',
    name: 'Risotto',
    description: 'Creamy rice dish.',
    rating: 3.9,
    price: 899,
    discountedPrice: 699,
    discountPercentage: 22,
    type: 'dish',
    category: 'Italian',
  },
  {
    id: 15,
    imgUrl: 'https://source.unsplash.com/300x300/?bruschetta',
    name: 'Bruschetta',
    description: 'Toasted bread snack.',
    rating: 3.6,
    price: 399,
    discountedPrice: 299,
    discountPercentage: 25,
    type: 'dish',
    category: 'Italian',
  },

  {
    id: 16,
    imgUrl: 'https://source.unsplash.com/300x300/?burger',
    name: 'Veg Burger',
    description: 'Crispy burger.',
    rating: 3.9,
    price: 299,
    discountedPrice: 199,
    discountPercentage: 33,
    type: 'dish',
    category: 'Fast Food',
  },
  {
    id: 17,
    imgUrl: 'https://source.unsplash.com/300x300/?fries',
    name: 'French Fries',
    description: 'Crispy fries.',
    rating: 4.1,
    price: 199,
    discountedPrice: 149,
    discountPercentage: 25,
    type: 'dish',
    category: 'Fast Food',
  },
  {
    id: 18,
    imgUrl: 'https://source.unsplash.com/300x300/?hotdog',
    name: 'Hot Dog',
    description: 'Grilled sausage roll.',
    rating: 3.7,
    price: 249,
    discountedPrice: 179,
    discountPercentage: 28,
    type: 'dish',
    category: 'Fast Food',
  },
  {
    id: 19,
    imgUrl: 'https://source.unsplash.com/300x300/?sandwich',
    name: 'Grilled Sandwich',
    description: 'Toasted sandwich.',
    rating: 4.2,
    price: 299,
    discountedPrice: 229,
    discountPercentage: 23,
    type: 'dish',
    category: 'Fast Food',
  },
  {
    id: 20,
    imgUrl: 'https://source.unsplash.com/300x300/?donut',
    name: 'Donuts',
    description: 'Sweet donuts.',
    rating: 4.5,
    price: 399,
    discountedPrice: 299,
    discountPercentage: 25,
    type: 'dessert',
    category: 'Fast Food',
  },

  {
    id: 21,
    imgUrl: 'https://source.unsplash.com/300x300/?salad',
    name: 'Green Salad',
    description: 'Fresh vegetables.',
    rating: 4.3,
    price: 399,
    discountedPrice: 299,
    discountPercentage: 25,
    type: 'dish',
    category: 'Healthy',
  },
  {
    id: 22,
    imgUrl: 'https://source.unsplash.com/300x300/?smoothie',
    name: 'Fruit Smoothie',
    description: 'Healthy drink.',
    rating: 4.6,
    price: 299,
    discountedPrice: 229,
    discountPercentage: 23,
    type: 'beverage',
    category: 'Healthy',
  },
  {
    id: 23,
    imgUrl: 'https://source.unsplash.com/300x300/?oats',
    name: 'Oats Bowl',
    description: 'Nutritious oats.',
    rating: 3.8,
    price: 249,
    discountedPrice: 179,
    discountPercentage: 28,
    type: 'dish',
    category: 'Healthy',
  },
  {
    id: 24,
    imgUrl: 'https://source.unsplash.com/300x300/?avocado-toast',
    name: 'Avocado Toast',
    description: 'Healthy toast.',
    rating: 4.1,
    price: 349,
    discountedPrice: 269,
    discountPercentage: 23,
    type: 'dish',
    category: 'Healthy',
  },
  {
    id: 25,
    imgUrl: 'https://source.unsplash.com/300x300/?quinoa',
    name: 'Quinoa Bowl',
    description: 'Protein rich meal.',
    rating: 3.9,
    price: 499,
    discountedPrice: 379,
    discountPercentage: 24,
    type: 'dish',
    category: 'Healthy',
  },

  {
    id: 26,
    imgUrl: 'https://source.unsplash.com/300x300/?coffee',
    name: 'Cold Coffee',
    description: 'Chilled coffee.',
    rating: 4.6,
    price: 199,
    discountedPrice: 149,
    discountPercentage: 25,
    type: 'beverage',
    category: 'Drinks',
  },
  {
    id: 27,
    imgUrl: 'https://source.unsplash.com/300x300/?juice',
    name: 'Orange Juice',
    description: 'Fresh juice.',
    rating: 4.2,
    price: 149,
    discountedPrice: 109,
    discountPercentage: 27,
    type: 'beverage',
    category: 'Drinks',
  },
  {
    id: 28,
    imgUrl: 'https://source.unsplash.com/300x300/?lemonade',
    name: 'Lemonade',
    description: 'Refreshing drink.',
    rating: 3.7,
    price: 99,
    discountedPrice: 79,
    discountPercentage: 20,
    type: 'beverage',
    category: 'Drinks',
  },
  {
    id: 29,
    imgUrl: 'https://source.unsplash.com/300x300/?milkshake',
    name: 'Milkshake',
    description: 'Creamy shake.',
    rating: 4.4,
    price: 249,
    discountedPrice: 189,
    discountPercentage: 24,
    type: 'beverage',
    category: 'Drinks',
  },
  {
    id: 30,
    imgUrl: 'https://source.unsplash.com/300x300/?tea',
    name: 'Masala Chai',
    description: 'Indian tea.',
    rating: 4.8,
    price: 79,
    discountedPrice: 59,
    discountPercentage: 25,
    type: 'beverage',
    category: 'Drinks',
  },
];

export default products;
